apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: mongodb-dev
    meta.helm.sh/release-namespace: default
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: mongodb-dev
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mongodb
  name: mongodb-dev
spec:
  ports:
  - name: mongodb
    port: 27017
    protocol: TCP
    targetPort: mongodb
  selector:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: mongodb-dev
    app.kubernetes.io/name: mongodb
  type: LoadBalancer

