apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    name: mongodb-dev
  name: mongodb-dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: efs-sc

